services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      target: development
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    environment:
      - PUBSUB_EMULATOR_HOST=0.0.0.0:8085
    networks:
      - gcp-network
    depends_on:
      - pubsub-emulator

  pubsub-emulator:
    build:
      context: .
      dockerfile: ./docker/pubsub-emulator/Dockerfile
    ports:
      - 8085:8085
    environment:
      - PUBSUB_EMULATOR_HOST=0.0.0.0:8085
    networks:
      - gcp-network

networks:
  gcp-network:
    driver: bridge
